name: Deploy app

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:
  # Triggers the workflow on push or pull request events, but only for the main branch.
  push:
    branches: main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  # This workflow contains a single job called build-deploy.
  build-deploy:
    # The type of runner that the job will run on.
    runs-on: ubuntu-latest
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the CI/CD job.
    steps:
      # Checks out your repo under $GITHUB_WORKSPACE.
      - name: Check out repository
        uses: actions/checkout@v2

      # Set up Quarto.
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      # Install Python and dependencies.
      - name: Install Python and Dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install jupyter
      - run: pip install -r requirements.txt

      # Render and publish the shiny app on the gh-pages branch.
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
